# Generated by Django 2.2.17 on 2020-11-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('annual_income', models.IntegerField(blank=True, null=True)),
                ('reason_to_adopt_cats', models.CharField(max_length=800)),
            ],
        ),
    ]
