# Generated by Django 2.2.10 on 2020-11-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
