# Generated by Django 2.2.10 on 2020-11-11 21:40

import apps.cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.cats.models._path),
        ),
    ]
