# Generated by Django 2.2.10 on 2020-11-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20201111_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cat',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
