# Generated by Django 2.2.10 on 2020-11-12 01:55

import apps.cats.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_auto_20201111_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to=apps.cats.models._path)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.Cat')),
            ],
        ),
    ]
