# Generated by Django 2.2.10 on 2020-11-13 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_auto_20201112_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_images',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cats.Cat'),
        ),
    ]
