# Generated by Django 2.2.10 on 2020-11-13 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0003_auto_20201112_1806'),
        ('cats', '0009_auto_20201112_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='adopter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adopters.Adopter'),
        ),
    ]
