# Generated by Django 2.2.10 on 2020-11-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='adopter',
        ),
    ]
