# Generated by Django 2.2.10 on 2020-11-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopters', '0002_auto_20201112_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopter',
            old_name='annual_income',
            new_name='an_income',
        ),
        migrations.RemoveField(
            model_name='adopter',
            name='reason_to_adopt_cats',
        ),
        migrations.AddField(
            model_name='adopter',
            name='reasons',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
